kind: Service                             
apiVersion: v1
metadata:
  name: sbm
  labels:
    app: sbm
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: sbm                    
  type: LoadBalancer                   
